### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by cobalt2727** [SpikeHD/SpikeHD#1]
Sorry for putting this here, wasn't sure where was best to contact you. I came across this article https://www.pcgamer.com/check-out-this-modders-doomed-quest-to-turn-a-nintendo-switch-into-a-steam-deck/ and figured you'd probably be interested to know that there *is* actually a (very experimental) way to get Steam working very, very slowly on the Switch by leveraging [box86](https://github.com/ptitSeb/box86) and [box64](https://github.com/ptitSeb/box64) - we've got a hidden script for it on the [L4T Megascript](https://github.com/cobalt2727/L4T-Megascript) that you can run using our Helper Script (check our wiki for documentation on that). I haven't actually used it myself - the other main contributor working on the Megascript did all the work on the Steam bit - but since it's obviously getting thrown through a translation layer performance is... not great. I've heard lighter stuff (e.g. Undertale, Celeste, Anodyne) should work fine though.

(Also, don't eject the SD card if you don't have to. The Switch's SD card reader is VERY susceptible to getting broken. If I remember correctly Hekate has an option to mount the SD on whatever computer you're hooked up to via USB...)

**Comment by CanadaHonk** [comment]
Switch SD card reader is mostly fine, just use FAT32 instead of exFAT (their driver is very dodgy).

**Comment by SpikeHD** [comment]
This is awesome thank you so much! I was planning on making a second one so this will be an awesome addition to the array of stuff I've already had planned

**Comment by theofficialgman** [comment]
you will have a bad time with the script

steam has removed the old login prompt fully with the update last week so you can't login.
also, the new big picture (steam deck looking) mode is now the only big picture mode and that does not work on box86 so no big picture either.

also don't even try running the script on your very broken install from that video. install L4T 5.0.0 fresh

**Comment by SpikeHD** [comment]
One can never know unless they try, unfortunate to hear that I was potentially only a week late to it working though lol

**Comment by theofficialgman** [comment]
do not try
I do not want to see your error log

I have seen your apt lists and what you have installed

**Comment by SpikeHD** [comment]
I will try anyways, and I had no intention of showing you my error log, trust me 😄

**Comment by theofficialgman** [comment]
> One can never know unless they try, unfortunate to hear that I was potentially only a week late to it working though lol

its been working on and off for the past year or so. the old big picture was great and worked fully for downloading, editing configs, etc. unfortunatly that is now fully gone.

the new UI is, I believe, fully 32bit x86 CEF (chromium embedded framework) and that is pretty much disabled in box86 since its known broken. maybe someday it will work again
